package seedu.address.logic.commands;

import seedu.address.logic.commands.exceptions.CommandException;

/**
 * Imports a list of persons in a save file generated by Export command.
 */
public class ImportCommand extends UndoableCommand {

    public static final String COMMAND_WORD = "import";

    public static final String MESSAGE_USAGE = COMMAND_WORD + ": adds a list of persons in an export XML file.\n"
        + "Parameters: FILEPATH\n"
        + "Example: " + COMMAND_WORD + " /Users/[USER NAME]/Documents/sharePersons.xml";

    private final String filePath;

    public ImportCommand(String filePath) {
        this.filePath = filePath;
    }

    @Override
    protected CommandResult executeUndoableCommand() throws CommandException {
        return null;
    }

    @Override
    public boolean equals(Object other) {
        return this == other
            || other instanceof ImportCommand
            && this.filePath.equals(((ImportCommand) other).filePath);
    }

}
