package seedu.address.logic.commands;

/**
 * Imports a list of persons in a save file generated by Export command.
 */
public class ImportCommand {

    public static final String COMMAND_WORD = "import";

    public static final String MESSAGE_USAGE = COMMAND_WORD + ": adds a list of persons in an export XML file.\n"
        + "Parameters: FILEPATH\n"
        + "Example: " + COMMAND_WORD + " /Users/[USER NAME]/Documents/sharePersons.xml";

}
